In [ ]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

data = {
    'Example 1': [4, 11],
    'Example 2': [8, 4],
    'Example 3': [13, 5],
    'Example 4': [7, 14]
}


df = pd.DataFrame(data, index=['X1', 'X2'])
print("Original Data:\n", df, "\n")

X = df.T.values
print("Data Matrix (examples as rows):\n", X, "\n")

scaler = StandardScaler(with_std=False)
X_centered = scaler.fit_transform(X)
print("Mean-Centered Data:\n", X_centered, "\n")



pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_centered)



print("Principal Components (each column = PC direction):\n", pca.components_.T, "\n")
print("Explained Variance:\n", pca.explained_variance_, "\n")
print("Explained Variance Ratio:\n", pca.explained_variance_ratio_, "\n")

df_pca = pd.DataFrame(X_pca, columns=['PC1', 'PC2'])
print("Transformed Dataset (in PCA space):\n", df_pca)


Original Data:
     Example 1  Example 2  Example 3  Example 4
X1          4          8         13          7
X2         11          4          5         14 

Data Matrix (examples as rows):
 [[ 4 11]
 [ 8  4]
 [13  5]
 [ 7 14]] 

Mean-Centered Data:
 [[-4.   2.5]
 [ 0.  -4.5]
 [ 5.  -3.5]
 [-1.   5.5]] 

Principal Components (each column = PC direction):
 [[-0.55738997  0.83025082]
 [ 0.83025082  0.55738997]] 

Explained Variance:
 [30.38486432  6.61513568] 

Explained Variance Ratio:
 [0.82121255 0.17878745] 

Transformed Dataset (in PCA space):
         PC1       PC2
0  4.305187 -1.927528
1 -3.736129 -2.508255
2 -5.692828  2.200389
3  5.123769  2.235394
